/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as SeedErrorProperty from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";

export declare namespace PropertyBasedError {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class PropertyBasedError {
    protected readonly _options: PropertyBasedError.Options;

    constructor(_options: PropertyBasedError.Options) {
        this._options = _options;
    }

    /**
     * GET request that always throws an error
     *
     * @param {PropertyBasedError.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SeedErrorProperty.PropertyBasedErrorTest}
     *
     * @example
     *     await client.propertyBasedError.throwError()
     */
    public throwError(requestOptions?: PropertyBasedError.RequestOptions): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__throwError(requestOptions));
    }

    private async __throwError(
        requestOptions?: PropertyBasedError.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "property-based-error",
            ),
            method: "GET",
            headers: mergeHeaders(this._options?.headers, requestOptions?.headers),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as any)?.["errorName"]) {
                case "PropertyBasedErrorTest":
                    throw new SeedErrorProperty.PropertyBasedErrorTest(
                        _response.error.body as SeedErrorProperty.PropertyBasedErrorTestBody,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SeedErrorPropertyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SeedErrorPropertyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SeedErrorPropertyTimeoutError(
                    "Timeout exceeded when calling GET /property-based-error.",
                );
            case "unknown":
                throw new errors.SeedErrorPropertyError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
